[package]
name = "yliproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0.86"
async-process = "2.2.4"

image = { version = "0.25.2", features = ["avif-native"] }
lazy_static = "1.5.0"
regex = "1.10.3"
reqwest = "0.12.5"
serenity = "0.12.2"
tokio = { version = "1.39.2", features = ["full"] }
